export const navigation_tabs = 'navigation.tabs'

export const screen_firsStart = 'screens.firsStart'
export const screen_acounts = 'screens.acounts'
export const screen_addCode = 'screens.addCode'
export const screen_addNumb = 'screens.addNumb'
export const screen_login = 'screens.login'
export const screen_chats = 'screens.chats'
export const screen_createProfile = 'screens.createProfile'
export const screen_createRule = 'screens.createRule'
export const screen_form = 'screens.form'
export const screen_home = 'screens.home'
export const screen_myProfile = 'screens.myProfile'
export const screen_listUser = 'screens.listUser'
export const screen_importChats = 'screens.importChats'
export const screen_notification = 'screens.notification'
export const screen_otp = 'screens.otp'
export const screen_menu = 'screens.menu'
export const screen_yourList = 'screens.yourList'
export const screen_userListFrom = 'screens.userListForm'
export const screen_staticWord = 'screens.staticWord'
export const screen_staticListChat = 'screens.staticListChat'
export const screen_staticChat = 'screens.staticChat'
export const screen_start = 'screens.start'
export const screen_rates = 'screens.rates'
export const screen_startInfo = 'screens.startInfo'
export const screen_addTelegInfo = 'screens.addTelegInfo'
export const screen_regTelegInfo = 'screens.regTelegInfo'

export const utils_util_name = 'utils.util_name'

//navigations
export const home_stack = 'navigation.homeStack'
export const index = 'navigation.index'
